### ISSUE TITLE
Incorrect save format: missing author field for encrypted; either WordList or SecretWordList (not both)

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-PyGame#171]
This makes your save/load inconsistent with the prescribed format and makes your game incompatible with everyone else.
<img width="1017" alt="incorrect-save-format-no-author-incompatible-with-other-teams" src="https://user-images.githubusercontent.com/2007799/234442274-c118acc7-d879-4a7c-992d-63fcab70d2fd.png">

**Comment by bennase** [comment]
Should be fixed with new PR (encrpytion3)

- added Author field for only encrypted lists
- WordList used only for unencrypted lists
- SecretWordList used only for encrypted lists
- implemented into CLI and GUI
